menu:
  title: "<dark_gray>ʀᴀɴᴅᴏᴍ ᴛᴇʟᴇᴘᴏʀᴛ"

destinations:
  overworld:
    name: "<bold><green>OVERWORLD</green></bold>"
    custom-model-data-start: 10001
    command: "betterrtp player %player% world"

  nether:
    name: "<bold><red>NETHER</red></bold>"
    custom-model-data-start: 10011
    command: "betterrtp player %player% world_nether"

  end:
    name: "<bold><light_purple>THE END</light_purple></bold>"
    custom-model-data-start: 10021
    command: "betterrtp player %player% world_the_end"
